package com.example.thirdapp.db;

import de.greenrobot.dao.DaoException;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table DOOR_KEY.
 *        "lock_name": "BLZXA150401111",
 "validity": null,
 "sdk_type_name": "雅静8#3单元"
 */
public class DoorKey {

    /** Not-null value. */
    private String sdk_id;
    private String app_key;
    private String user_id;
    private String agtcode;
    private String algorithmVer;
    private String lock_name;
    private String community;
    private String lock_id;
    private String state;
    private String reg_time;
    private String sdk_type_id;
    private String sdk_number;
    private String sdk_fid;
    private String sdk_type_name;
    private String history_id;
    private String pid;
    private String validity;
    private String ancno;
    private String auname;
    private String auno;
    private String autel;
    private String aucommon;
    private String time;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient DoorKeyDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DoorKey() {
    }

    public DoorKey(String sdk_id) {
        this.sdk_id = sdk_id;
    }

    public DoorKey(String sdk_id, String app_key, String user_id, String agtcode, String algorithmVer, String lock_name, String community, String lock_id, String state, String reg_time, String sdk_type_id, String sdk_number, String sdk_fid, String sdk_type_name, String history_id, String pid, String validity, String ancno, String auname, String auno, String autel, String aucommon, String time) {
        this.sdk_id = sdk_id;
        this.app_key = app_key;
        this.user_id = user_id;
        this.agtcode = agtcode;
        this.algorithmVer = algorithmVer;
        this.lock_name = lock_name;
        this.community = community;
        this.lock_id = lock_id;
        this.state = state;
        this.reg_time = reg_time;
        this.sdk_type_id = sdk_type_id;
        this.sdk_number = sdk_number;
        this.sdk_fid = sdk_fid;
        this.sdk_type_name = sdk_type_name;
        this.history_id = history_id;
        this.pid = pid;
        this.validity = validity;
        this.ancno = ancno;
        this.auname = auname;
        this.auno = auno;
        this.autel = autel;
        this.aucommon = aucommon;
        this.time = time;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getDoorKeyDao() : null;
    }

    /** Not-null value. */
    public String getSdk_id() {
        return sdk_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSdk_id(String sdk_id) {
        this.sdk_id = sdk_id;
    }

    public String getApp_key() {
        return app_key;
    }

    public void setApp_key(String app_key) {
        this.app_key = app_key;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getAgtcode() {
        return agtcode;
    }

    public void setAgtcode(String agtcode) {
        this.agtcode = agtcode;
    }

    public String getAlgorithmVer() {
        return algorithmVer;
    }

    public void setAlgorithmVer(String algorithmVer) {
        this.algorithmVer = algorithmVer;
    }

    public String getLock_name() {
        return lock_name;
    }

    public void setLock_name(String lock_name) {
        this.lock_name = lock_name;
    }

    public String getCommunity() {
        return community;
    }

    public void setCommunity(String community) {
        this.community = community;
    }

    public String getLock_id() {
        return lock_id;
    }

    public void setLock_id(String lock_id) {
        this.lock_id = lock_id;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getReg_time() {
        return reg_time;
    }

    public void setReg_time(String reg_time) {
        this.reg_time = reg_time;
    }

    public String getSdk_type_id() {
        return sdk_type_id;
    }

    public void setSdk_type_id(String sdk_type_id) {
        this.sdk_type_id = sdk_type_id;
    }

    public String getSdk_number() {
        return sdk_number;
    }

    public void setSdk_number(String sdk_number) {
        this.sdk_number = sdk_number;
    }

    public String getSdk_fid() {
        return sdk_fid;
    }

    public void setSdk_fid(String sdk_fid) {
        this.sdk_fid = sdk_fid;
    }

    public String getSdk_type_name() {
        return sdk_type_name;
    }

    public void setSdk_type_name(String sdk_type_name) {
        this.sdk_type_name = sdk_type_name;
    }

    public String getHistory_id() {
        return history_id;
    }

    public void setHistory_id(String history_id) {
        this.history_id = history_id;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getValidity() {
        return validity;
    }

    public void setValidity(String validity) {
        this.validity = validity;
    }

    public String getAncno() {
        return ancno;
    }

    public void setAncno(String ancno) {
        this.ancno = ancno;
    }

    public String getAuname() {
        return auname;
    }

    public void setAuname(String auname) {
        this.auname = auname;
    }

    public String getAuno() {
        return auno;
    }

    public void setAuno(String auno) {
        this.auno = auno;
    }

    public String getAutel() {
        return autel;
    }

    public void setAutel(String autel) {
        this.autel = autel;
    }

    public String getAucommon() {
        return aucommon;
    }

    public void setAucommon(String aucommon) {
        this.aucommon = aucommon;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
